name: Onboading Improvement
description: Create an issue about existing onboarding content
title: "[Improvement]: "
labels: ["improvement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this suggestion!
  - type: checkboxes
    id: terms
    attributes:
      label: Role
      description: Which roles are affected?
      options:
        - label: Accounts Support Specialists
        - label: Customer Reliability Engineers
        - label: Enterprise Support Engineers
        - label: GHAE Support Engineers
        - label: Premium Support Engineers
        - label: Support Contractors
        - label: Technical Support Engineers
  - type: textarea
    attributes:
      label: What article(s) is affected?
      description: Please link to the article(s) in the docs that you'd like to update.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Are you willing to open a PR to make this fix? If not, do you know anyone (Hubber or not, we're open source!) who's willing to help write this documentation?
      description: |
        Based on your answer, the Doctocat who triages this issue will do one of the following:

        • Review your issue and confirm the changes listed here cover all affected areas of the docs. Then, they'll invite you to open a PR and give you guidance on how to do so! This is the quickest way to get things changed.
        • Transfer this issue to our open source repo for the community to open a PR. We never know how long it will take for someone to pick up the issue.
        • Triage to our backlog. We'll get to it as soon as we can.
        • Close this issue as something we're unable to prioritize right now. Sometimes, we just can't prioritize changes, but if we make sweeping updates to this area of the docs, we'll scan through old issues if possible.
      placeholder: Mention the handle of the person who will open the PR.
    validations:
      required: true
