name: Onboading Improvement
description: Create an issue about existing onboarding content
title: "[Improvement]: "
labels: ["improvement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this suggestion!
  - type: checkboxes
    id: terms
    attributes:
      label: Role
      description: Which roles are affected?
      options:
        - label: Accounts Support Specialists
        - label: Customer Reliability Engineers
        - label: Enterprise Support Engineers
        - label: GHAE Support Engineers
        - label: Premium Support Engineers
        - label: Support Contractors
        - label: Technical Support Engineers
  - type: textarea
    attributes:
      label: What article(s) is affected?
      description: Please link to the article(s) that you'd like to update (source files for the issue templates can be found in the in https://github.com/github/onboarder-next/ repository).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Are you willing to open a PR to make this fix? 
      description: |
        Based on your answer, the Octocat who triages this issue will do one of the following:

        • Review your issue and confirm the changes listed here cover all affected areas of the docs. Then, they'll invite you to open a PR and give you guidance on how to do so! This is the quickest way to get things changed.
        • Triage to our backlog. We'll get to it as soon as we can.
        • If you are willing to work on the PR please include your buddies handle alongside your own.
      placeholder: |
        • Willing to open a PR: Yes/No
        • Your handle: 
        • Your buddies handle: 
    validations:
      required: true
