name: Onboading Improvement
description: Create an issue about existing onboarding content
title: "[Improvement]: "
labels: ["improvement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this suggestion!
  - type: checkboxes
    id: terms
    attributes:
      label: Role
      description: Which roles are affected?
      options:
        - label: Accounts Support Specialists
        - label: Customer Reliability Engineers
        - label: Enterprise Support Engineers
        - label: GHAE Support Engineers
        - label: Premium Support Engineers
        - label: Support Contractors
        - label: Technical Support Engineers
  - type: textarea
    attributes:
      label: What article(s) is affected?
      description: Please link to the article(s) in the docs that you'd like to update.
    validations:
      required: true
