name: Onboading Improvement
description: Create an issue about existing onboarding content
title: "[Improvement]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this suggestion!
  - type: checkboxes
    id: terms
    attributes:
      label: Role
      description: Which roles are affected?
      options:
        - label: Premium Support Engineer
        labels: "premium-support"
        - label: Support Contractors
